### Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.2.2'

### Getting the data

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

### Q2. Records count
How many records are in the dataset?

In [6]:
len(df)

2160

### Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [7]:
df['Brand'].nunique(dropna=True)

27

### Q4. Missing values
How many columns in the dataset have missing values?

In [8]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [9]:
dell_laptops = df[df['Brand']=='Dell']

dell_laptops['Final Price'].max()

np.float64(3936.0)

### Q6. Median value of Screen
1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again. Has it changed?

Hint: refer to existing mode and median functions to complete the task.

In [10]:
median = df['Screen'].median()
mode = df['Screen'].mode()


new_screen_col = df['Screen'].fillna(mode)

new_median = new_screen_col.median()
new_mode = new_screen_col.mode()

dict = {
    "Median": median,
    "Mode" : mode,
    "New Median": new_median,
    "New Mode" : new_mode
}
dict

{'Median': np.float64(15.6),
 'Mode': 0    15.6
 Name: Screen, dtype: float64,
 'New Median': np.float64(15.6),
 'New Mode': 0    15.6
 Name: Screen, dtype: float64}

### Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [40]:
import numpy as np

In [117]:
innjoo = df[df['Brand'].str.contains('Innjoo')] 
innjoo = innjoo[["RAM","Storage","Screen"]]

X = np.array(innjoo)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [127]:
XTX = X.T @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [128]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [129]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [130]:
w = XTX_inv @ X.T @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [131]:
result_sum = np.sum(w)

print(f"The sum of all elements in w is: {result_sum}")

The sum of all elements in w is: 91.2998806299555


In [124]:
(XTX_inv @ X.T) @ y

array([45.58076606,  0.42783519, 45.29127938])